### PR TITLE
Improve the cache partition

### PR DESCRIPTION
**Pull request by SleepBook**
Change the cache partitioning to support up to 128 ways, fix bugs and improve the code comments.

### CODE REVIEW

**Comment by spruett** [comment]
Can you run `make release` in the src directory and update the pull request with the resulting file changes?

`make release` will run clang format, which will enforce some formatting guidelines on the code.

**Comment by SleepBook** [comment]
I run `make clang-format` but seems it changes the format for a lot of files I didn't touch. Can this be because the different version of `clang-format` I am using and you used? Shall I still commit the code changes?

**Comment by chestercai1995** [comment]
You should checkout the new version of clang format file under bin
directory. The older version does not skip the submodules in scarab which
is what you are seeing now.

**Comment by SleepBook** [comment]
I already merged the changes from the master in this PR, and I believe that will run the up-to-date `run_clang_format_on_all.sh` under bin. Here is the list of files which change format after I run `make  clang-format`:
```
modified:   ../src/addr_trans.c
	modified:   ../src/bp/bp.h
	modified:   ../src/bp/bp_conf.c
	modified:   ../src/bp/bp_targ_mech.c
	modified:   ../src/cmp_model.c
	modified:   ../src/cmp_model_support.c
	modified:   ../src/dcache_stage.c
	modified:   ../src/dcache_stage.h
	modified:   ../src/dvfs/perf_pred.c
	modified:   ../src/exec_ports.c
	modified:   ../src/exec_stage.h
	modified:   ../src/globals/assert.h
	modified:   ../src/globals/utils.c
	modified:   ../src/icache_stage.h
	modified:   ../src/isa/isa_macros.h
	modified:   ../src/libs/cache_lib.c
	modified:   ../src/libs/malloc_lib.c
	modified:   ../src/map.c
	modified:   ../src/memory/cache_part.c
	modified:   ../src/memory/mem_req.h
	modified:   ../src/memory/memory.c
	modified:   ../src/memory/memory.h
	modified:   ../src/model.h
	modified:   ../src/optimizer2.c
	modified:   ../src/param_parser.c
	modified:   ../src/pin/pin_lib/message_queue_interface_lib.cc
	modified:   ../src/pin/pin_lib/uop_generator.c
	modified:   ../src/pin/pin_lib/x87_stack_delta.cc
	modified:   ../src/power/power_scarab_config.cc
	modified:   ../src/prefetcher/pref_stream.c
	modified:   ../src/prefetcher/pref_stride.c
	modified:   ../src/prefetcher/stream_pref.c
	modified:   ../src/sim.c
	modified:   ../src/stat_mon.c
	modified:   ../src/test/server_client_socket_test.cc
	modified:   ../utils/checkpoint/loader/checkpoint_reader.cc
	modified:   ../utils/checkpoint/loader/hconfig.c
	modified:   ../utils/checkpoint/loader/test_memcpy.cc
	modified:   ../utils/qsort/libc_qsort.c
```
I am using clang-format 6.0.0

**Comment by siavashzk** [comment]
Yeah, this is probably due to a different clang version. We use Clang 5. And I've previously seen that different clang version work slightly  differently. Can you install clang 5 and edit bin/run_clang_format_on_all.sh to point to clang 5 instead?

**Comment by SleepBook** [comment]
Great, seems it's working now, thanks everyone for the help

**Pull request merged**
